<?php
	
//email information
define('EMAIL_SERVER','smtp.exmail.qq.com');
define('EMAIL_PORT','25');
define('EMAIL_NOREPLY',[
    'noreply@shuofou.net',
    'noreply1@shuofou.net',
    'noreply2@shuofou.net',
    'noreply3@shuofou.net',
    'noreply4@shuofou.net',
    'noreply5@shuofou.net',
    'noreply6@shuofou.net',
    'noreply7@shuofou.net',
    'noreply8@shuofou.net',
    'noreply9@shuofou.net',
    'noreply10@shuofou.net',
    'noreply11@shuofou.net',
    'noreply12@shuofou.net',
    'noreply13@shuofou.net',
    'noreply14@shuofou.net',
    'noreply15@shuofou.net',
    'noreply16@shuofou.net',
    'noreply17@shuofou.net',
    'noreply18@shuofou.net',
    'noreply19@shuofou.net',
    'noreply20@shuofou.net',
    'noreply21@shuofou.net',
    'noreply22@shuofou.net',
    'noreply23@shuofou.net',
    'noreply24@shuofou.net',
    'noreply25@shuofou.net',
    'noreply26@shuofou.net',
    'noreply27@shuofou.net',
    'noreply28@shuofou.net',
    'noreply29@shuofou.net',
    'noreply30@shuofou.net',
    'noreply31@shuofou.net',
    'noreply32@shuofou.net',
    'noreply33@shuofou.net',
    'noreply34@shuofou.net',
    'noreply35@shuofou.net',
    'noreply36@shuofou.net',
    'noreply37@shuofou.net',
    'noreply38@shuofou.net',
    'noreply39@shuofou.net',
]);
define('EMAIL_NOREPLY_PASSWORD','Woniu1117');
define('EMAIL_CONTACT','contact@shuofou.net');